/*
**Oracle 12c Autoincrement with Identity
Previous versions of Oracle did not have the equivalent of an 
AutoNumber or Identity function of other databases. 
The 12c database introduces the ability define an identity clause 
against a table column defined using a numeric type. 
The syntax is show below.

Using BY DEFAULT allows you to use the identity 
if the column isn't referenced in the insert statement, 
but if the column is referenced, the specified value will be used 
in place of the identity. 
*/

  CREATE TABLE "ORA1"."BULLHORN" 
   (	"POSTID" INT GENERATED BY DEFAULT ON NULL AS IDENTITY, 
	"PDATE" DATE,  
	"POST" VARCHAR2(140 BYTE), 
	"USERID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;



create sequence SEQ_GEN_IDENTITY
start with 1
increment by 1
cache 10;

SELECT SEQ_GEN_IDENTITY.NEXTVAL FROM DUAL;
                        
Insert into ORA1.BULLHORN (PDATE,POST,USERID) values (to_date('05-APR-16','DD-MON-RR'),'this is a test 4',1);


drop sequence ora1.SEQ_GEN_IDENTITY;
                             
create table identity_test (                                                       
id number generated by default on null as identity,
description varchar(30)
);
insert into identity_test (description) values ('just testing4');
insert into identity_test (description) values ('just testing3');
select * from identity_test;
  
